// flow-typed signature: 3c8509e66d5cd59d08d1e2ffbca34bc8
// flow-typed version: <<STUB>>/babel-plugin-transform-react-pure-class-to-function_v^1.0.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-react-pure-class-to-function'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-react-pure-class-to-function' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-react-pure-class-to-function/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-react-pure-class-to-function/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-pure-class-to-function/lib/index'>;
}
