// flow-typed signature: 56c9559b0460ce3d357ae9d1577d4479
// flow-typed version: <<STUB>>/pizzicato_v^0.6.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pizzicato'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pizzicato' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pizzicato/distr/Pizzicato' {
  declare module.exports: any;
}

declare module 'pizzicato/distr/Pizzicato.min' {
  declare module.exports: any;
}

declare module 'pizzicato/karma.conf' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Effects' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Effects/Compressor' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Effects/Convolver' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Effects/Delay' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Effects/Distortion' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Effects/DubDelay' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Effects/Filters' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Effects/Flanger' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Effects/PingPongDelay' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Effects/Quadrafuzz' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Effects/Reverb' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Effects/RingModulator' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Effects/StereoPanner' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Effects/Tremolo' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Events' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Group' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Pizzicato' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Shims' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Sound' {
  declare module.exports: any;
}

declare module 'pizzicato/src/Util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pizzicato/distr/Pizzicato.js' {
  declare module.exports: $Exports<'pizzicato/distr/Pizzicato'>;
}
declare module 'pizzicato/distr/Pizzicato.min.js' {
  declare module.exports: $Exports<'pizzicato/distr/Pizzicato.min'>;
}
declare module 'pizzicato/karma.conf.js' {
  declare module.exports: $Exports<'pizzicato/karma.conf'>;
}
declare module 'pizzicato/src/Effects.js' {
  declare module.exports: $Exports<'pizzicato/src/Effects'>;
}
declare module 'pizzicato/src/Effects/Compressor.js' {
  declare module.exports: $Exports<'pizzicato/src/Effects/Compressor'>;
}
declare module 'pizzicato/src/Effects/Convolver.js' {
  declare module.exports: $Exports<'pizzicato/src/Effects/Convolver'>;
}
declare module 'pizzicato/src/Effects/Delay.js' {
  declare module.exports: $Exports<'pizzicato/src/Effects/Delay'>;
}
declare module 'pizzicato/src/Effects/Distortion.js' {
  declare module.exports: $Exports<'pizzicato/src/Effects/Distortion'>;
}
declare module 'pizzicato/src/Effects/DubDelay.js' {
  declare module.exports: $Exports<'pizzicato/src/Effects/DubDelay'>;
}
declare module 'pizzicato/src/Effects/Filters.js' {
  declare module.exports: $Exports<'pizzicato/src/Effects/Filters'>;
}
declare module 'pizzicato/src/Effects/Flanger.js' {
  declare module.exports: $Exports<'pizzicato/src/Effects/Flanger'>;
}
declare module 'pizzicato/src/Effects/PingPongDelay.js' {
  declare module.exports: $Exports<'pizzicato/src/Effects/PingPongDelay'>;
}
declare module 'pizzicato/src/Effects/Quadrafuzz.js' {
  declare module.exports: $Exports<'pizzicato/src/Effects/Quadrafuzz'>;
}
declare module 'pizzicato/src/Effects/Reverb.js' {
  declare module.exports: $Exports<'pizzicato/src/Effects/Reverb'>;
}
declare module 'pizzicato/src/Effects/RingModulator.js' {
  declare module.exports: $Exports<'pizzicato/src/Effects/RingModulator'>;
}
declare module 'pizzicato/src/Effects/StereoPanner.js' {
  declare module.exports: $Exports<'pizzicato/src/Effects/StereoPanner'>;
}
declare module 'pizzicato/src/Effects/Tremolo.js' {
  declare module.exports: $Exports<'pizzicato/src/Effects/Tremolo'>;
}
declare module 'pizzicato/src/Events.js' {
  declare module.exports: $Exports<'pizzicato/src/Events'>;
}
declare module 'pizzicato/src/Group.js' {
  declare module.exports: $Exports<'pizzicato/src/Group'>;
}
declare module 'pizzicato/src/Pizzicato.js' {
  declare module.exports: $Exports<'pizzicato/src/Pizzicato'>;
}
declare module 'pizzicato/src/Shims.js' {
  declare module.exports: $Exports<'pizzicato/src/Shims'>;
}
declare module 'pizzicato/src/Sound.js' {
  declare module.exports: $Exports<'pizzicato/src/Sound'>;
}
declare module 'pizzicato/src/Util.js' {
  declare module.exports: $Exports<'pizzicato/src/Util'>;
}
