export default {
  'Pentatonic Scale': [
    { value: 'scheme_Pentatonic_GB', label: 'Pentatonic Scale in Gb' },
    { value: 'scheme_Pentatonic_F', label: 'Pentatonic Scale in F' },
    { value: 'scheme_Pentatonic_E', label: 'Pentatonic Scale in E' },
    { value: 'scheme_Pentatonic_EB', label: 'Pentatonic Scale in Eb' },
    { value: 'scheme_Pentatonic_D', label: 'Pentatonic Scale in D' },
    { value: 'scheme_Pentatonic_DB', label: 'Pentatonic Scale in Db' },
    { value: 'scheme_Pentatonic_C', label: 'Pentatonic Scale in C' },
    { value: 'scheme_Pentatonic_B', label: 'Pentatonic Scale in B' },
    { value: 'scheme_Pentatonic_BB', label: 'Pentatonic Scale in Bb' },
    { value: 'scheme_Pentatonic_A', label: 'Pentatonic Scale in A' },
    { value: 'scheme_Pentatonic_AB', label: 'Pentatonic Scale in Ab' },
    { value: 'scheme_Pentatonic_G', label: 'Pentatonic Scale in G' }
  ],
  'Gyemyeonjo Scale': [
    { value: 'scheme_Gyemyeonjo_GB', label: 'Gyemyeonjo Scale in Gb' },
    { value: 'scheme_Gyemyeonjo_F', label: 'Gyemyeonjo Scale in F' },
    { value: 'scheme_Gyemyeonjo_E', label: 'Gyemyeonjo Scale in E' },
    { value: 'scheme_Gyemyeonjo_EB', label: 'Gyemyeonjo Scale in Eb' },
    { value: 'scheme_Gyemyeonjo_D', label: 'Gyemyeonjo Scale in D' },
    { value: 'scheme_Gyemyeonjo_DB', label: 'Gyemyeonjo Scale in Db' },
    { value: 'scheme_Gyemyeonjo_C', label: 'Gyemyeonjo Scale in C' },
    { value: 'scheme_Gyemyeonjo_B', label: 'Gyemyeonjo Scale in B' },
    { value: 'scheme_Gyemyeonjo_BB', label: 'Gyemyeonjo Scale in Bb' },
    { value: 'scheme_Gyemyeonjo_A', label: 'Gyemyeonjo Scale in A' },
    { value: 'scheme_Gyemyeonjo_AB', label: 'Gyemyeonjo Scale in Ab' },
    { value: 'scheme_Gyemyeonjo_G', label: 'Gyemyeonjo Scale in G' }
  ],
  'In Sen Scale': [
    { value: 'scheme_In_GB', label: 'In Sen Scale in Gb' },
    { value: 'scheme_In_F', label: 'In Sen Scale in F' },
    { value: 'scheme_In_E', label: 'In Sen Scale in E' },
    { value: 'scheme_In_EB', label: 'In Sen Scale in Eb' },
    { value: 'scheme_In_D', label: 'In Sen Scale in D' },
    { value: 'scheme_In_DB', label: 'In Sen Scale in Db' },
    { value: 'scheme_In_C', label: 'In Sen Scale in C' },
    { value: 'scheme_In_B', label: 'In Sen Scale in B' },
    { value: 'scheme_In_BB', label: 'In Sen Scale in Bb' },
    { value: 'scheme_In_A', label: 'In Sen Scale in A' },
    { value: 'scheme_In_AB', label: 'In Sen Scale in Ab' },
    { value: 'scheme_In_G', label: 'In Sen Scale in G' }
  ],
  'Ionian Major 9': [
    { value: 'scheme_Ionian9_GB', label: 'Ionian Major 9 in Gb' },
    { value: 'scheme_Ionian9_F', label: 'Ionian Major 9 in F' },
    { value: 'scheme_Ionian9_E', label: 'Ionian Major 9 in E' },
    { value: 'scheme_Ionian9_EB', label: 'Ionian Major 9 in Eb' },
    { value: 'scheme_Ionian9_D', label: 'Ionian Major 9 in D' },
    { value: 'scheme_Ionian9_DB', label: 'Ionian Major 9 in Db' },
    { value: 'scheme_Ionian9_C', label: 'Ionian Major 9 in C' },
    { value: 'scheme_Ionian9_B', label: 'Ionian Major 9 in B' },
    { value: 'scheme_Ionian9_BB', label: 'Ionian Major 9 in Bb' },
    { value: 'scheme_Ionian9_A', label: 'Ionian Major 9 in A' },
    { value: 'scheme_Ionian9_AB', label: 'Ionian Major 9 in Ab' },
    { value: 'scheme_Ionian9_G', label: 'Ionian Major 9 in G' }
  ],
  'Hirajoshi Scale': [
    { value: 'scheme_Hirajoshi_GB', label: 'Hirajoshi Scale in Gb' },
    { value: 'scheme_Hirajoshi_F', label: 'Hirajoshi Scale in F' },
    { value: 'scheme_Hirajoshi_E', label: 'Hirajoshi Scale in E' },
    { value: 'scheme_Hirajoshi_EB', label: 'Hirajoshi Scale in Eb' },
    { value: 'scheme_Hirajoshi_D', label: 'Hirajoshi Scale in D' },
    { value: 'scheme_Hirajoshi_DB', label: 'Hirajoshi Scale in Db' },
    { value: 'scheme_Hirajoshi_C', label: 'Hirajoshi Scale in C' },
    { value: 'scheme_Hirajoshi_B', label: 'Hirajoshi Scale in B' },
    { value: 'scheme_Hirajoshi_BB', label: 'Hirajoshi Scale in Bb' },
    { value: 'scheme_Hirajoshi_A', label: 'Hirajoshi Scale in A' },
    { value: 'scheme_Hirajoshi_AB', label: 'Hirajoshi Scale in Ab' },
    { value: 'scheme_Hirajoshi_G', label: 'Hirajoshi Scale in G' }
  ],
  Major: [
    { value: 'scheme_Major_GB', label: 'Gb Major' },
    { value: 'scheme_Major_F', label: 'F Major' },
    { value: 'scheme_Major_E', label: 'E Major' },
    { value: 'scheme_Major_EB', label: 'Eb Major' },
    { value: 'scheme_Major_D', label: 'D Major' },
    { value: 'scheme_Major_DB', label: 'Db Major' },
    { value: 'scheme_Major_C', label: 'C Major' },
    { value: 'scheme_Major_B', label: 'B Major' },
    { value: 'scheme_Major_BB', label: 'Bb Major' },
    { value: 'scheme_Major_A', label: 'A Major' },
    { value: 'scheme_Major_AB', label: 'Ab Major' },
    { value: 'scheme_Major_G', label: 'G Major' }
  ],
  'Minor (Melodic)': [
    { value: 'scheme_MinorMelodic_GB', label: 'Gb Minor (Melodic)' },
    { value: 'scheme_MinorMelodic_F', label: 'F Minor (Melodic)' },
    { value: 'scheme_MinorMelodic_E', label: 'E Minor (Melodic)' },
    { value: 'scheme_MinorMelodic_EB', label: 'Eb Minor (Melodic)' },
    { value: 'scheme_MinorMelodic_D', label: 'D Minor (Melodic)' },
    { value: 'scheme_MinorMelodic_DB', label: 'Db Minor (Melodic)' },
    { value: 'scheme_MinorMelodic_C', label: 'C Minor (Melodic)' },
    { value: 'scheme_MinorMelodic_B', label: 'B Minor (Melodic)' },
    { value: 'scheme_MinorMelodic_BB', label: 'Bb Minor (Melodic)' },
    { value: 'scheme_MinorMelodic_A', label: 'A Minor (Melodic)' },
    { value: 'scheme_MinorMelodic_AB', label: 'Ab Minor (Melodic)' },
    { value: 'scheme_MinorMelodic_G', label: 'G Minor (Melodic)' }
  ],
  Others: [
    { value: 'scheme_Angry', label: 'Angry Mode' },
    { value: 'scheme_Mysterious', label: 'Mysterious Mode' },
    { value: 'scheme_Nature', label: 'Nature Mode' }
  ]
};
