/* eslint quote-props: ["error", "consistent"] */

// Animal sound

export default {
  'a': { instrument: 'animalhigh', note: 'chipmunk' },
  'b': { instrument: 'animalhigh', note: 'cougar' },
  'c': { instrument: 'animalhigh', note: 'crow' },
  'd': { instrument: 'animalhigh', note: 'dog' },
  'e': { instrument: 'animalhigh', note: 'dolphin' },
  'f': { instrument: 'animalhigh', note: 'frog' },
  'g': { instrument: 'animalhigh', note: 'greyfox' },
  'h': { instrument: 'animalhigh', note: 'guineapig' },
  'i': { instrument: 'animalhigh', note: 'hawk' },
  'j': { instrument: 'animalhigh', note: 'horse' },
  'k': { instrument: 'animalhigh', note: 'kitten' },
  'l': { instrument: 'animalhigh', note: 'lemur' },
  'm': { instrument: 'animalhigh', note: 'mice' },
  'n': { instrument: 'animalhigh', note: 'parrot' },
  'o': { instrument: 'animalhigh', note: 'peacock' },
  'p': { instrument: 'animalhigh', note: 'puppy' },
  'q': { instrument: 'animalhigh', note: 'puppy2' },
  'r': { instrument: 'animalhigh', note: 'raccoon' },
  's': { instrument: 'animalhigh', note: 'rhinos' },
  't': { instrument: 'animalhigh', note: 'rooster' },
  'u': { instrument: 'animalhigh', note: 'seagull' },
  'v': { instrument: 'animalhigh', note: 'songbird' },
  'w': { instrument: 'animalhigh', note: 'sparrow' },
  'x': { instrument: 'animalhigh', note: 'squirrel' },
  'y': { instrument: 'animalhigh', note: 'wolf' },
  'z': { instrument: 'animalhigh', note: 'zebra' },
  'A': { instrument: 'animalmid', note: 'bats' },
  'B': { instrument: 'animalmid', note: 'bee' },
  'C': { instrument: 'animalmid', note: 'camel' },
  'D': { instrument: 'animalmid', note: 'cat' },
  'E': { instrument: 'animalmid', note: 'chicken' },
  'F': { instrument: 'animalmid', note: 'chimpanzee' },
  'G': { instrument: 'animalmid', note: 'coyote' },
  'H': { instrument: 'animalmid', note: 'crocodile' },
  'I': { instrument: 'animalmid', note: 'dog' },
  'J': { instrument: 'animalmid', note: 'duck' },
  'K': { instrument: 'animalmid', note: 'fly' },
  'L': { instrument: 'animalmid', note: 'geese' },
  'M': { instrument: 'animalmid', note: 'goat' },
  'N': { instrument: 'animalmid', note: 'hound' },
  'O': { instrument: 'animalmid', note: 'lemur' },
  'P': { instrument: 'animalmid', note: 'lynx' },
  'Q': { instrument: 'animalmid', note: 'penguin' },
  'R': { instrument: 'animalmid', note: 'pigeon' },
  'S': { instrument: 'animalmid', note: 'rattlesnake' },
  'T': { instrument: 'animalmid', note: 'seal' },
  'U': { instrument: 'animalmid', note: 'seal2' },
  'V': { instrument: 'animalmid', note: 'sealions' },
  'W': { instrument: 'animalmid', note: 'sheep' },
  'X': { instrument: 'animalmid', note: 'swan' },
  'Y': { instrument: 'animalmid', note: 'turkey' },
  'Z': { instrument: 'animalmid', note: 'wolf' },
  '$': { instrument: 'animallow', note: 'alligator' },
  ',': { instrument: 'animallow', note: 'angryowl' },
  '/': { instrument: 'animallow', note: 'bear' },
  '\\': { instrument: 'animallow', note: 'cattle' },
  ':': { instrument: 'animallow', note: 'cheeta' },
  ';': { instrument: 'animallow', note: 'cow' },
  '-': { instrument: 'animallow', note: 'deer' },
  '+': { instrument: 'animallow', note: 'donkey' },
  '|': { instrument: 'animallow', note: 'elephant' },
  '{': { instrument: 'animallow', note: 'grizzlybear' },
  '}': { instrument: 'animallow', note: 'hoppo' },
  '[': { instrument: 'animallow', note: 'hog' },
  ']': { instrument: 'animallow', note: 'hyena' },
  '%': { instrument: 'animallow', note: 'jaguar' },
  '&': { instrument: 'animallow', note: 'koala' },
  '*': { instrument: 'animallow', note: 'leopard' },
  '^': { instrument: 'animallow', note: 'lion' },
  '#': { instrument: 'animallow', note: 'llama' },
  '!': { instrument: 'animallow', note: 'longhorn' },
  '@': { instrument: 'animallow', note: 'moose' },
  '(': { instrument: 'animallow', note: 'ocelet' },
  ')': { instrument: 'animallow', note: 'ostrich' },
  '=': { instrument: 'animallow', note: 'owl' },
  '~': { instrument: 'animallow', note: 'pig' },
  '`': { instrument: 'animallow', note: 'tiger' },
  '_': { instrument: 'animallow', note: 'walrus' },
  '"': { instrument: 'animallow', note: 'alligator' },
  "'": { instrument: 'animallow', note: 'angryowl' },
  '<': { instrument: 'animallow', note: 'bear' },
  '>': { instrument: 'animallow', note: 'cattle' },
  '.': { instrument: 'animallow', note: 'cheeta' },
  '?': { instrument: 'animallow', note: 'cow' },
  '0': { instrument: 'animallow', note: 'deer' },
  '1': { instrument: 'animallow', note: 'donkey' },
  '2': { instrument: 'animallow', note: 'elephant' },
  '3': { instrument: 'animallow', note: 'grizzlybear' },
  '4': { instrument: 'animallow', note: 'hippo' },
  '5': { instrument: 'animallow', note: 'hog' },
  '6': { instrument: 'animallow', note: 'hyena' },
  '7': { instrument: 'animallow', note: 'jaguar' },
  '8': { instrument: 'animallow', note: 'koala' },
  '9': { instrument: 'animallow', note: 'leopard' },
  // '$': { instrument: 'animallow', note: 'alligator' },
  // ',': { instrument: 'animallow', note: 'angryowl' },
  // '/': { instrument: 'animallow', note: 'bear' },
  // '\\': { instrument: 'animallow', note: 'cattle' },
  // ':': { instrument: 'animallow', note: 'cheeta' },
  // ';': { instrument: 'animallow', note: 'cow' },
  // '-': { instrument: 'animallow', note: 'deer' },
  // '+': { instrument: 'animallow', note: 'donkey' },
  // '|': { instrument: 'animallow', note: 'elephant' },
  // '{': { instrument: 'animallow', note: 'grizzlybear' },
  // '}': { instrument: 'animallow', note: 'hoppo' },
  // '[': { instrument: 'animallow', note: 'hog' },
  // ']': { instrument: 'animallow', note: 'hyena' },
  // '%': { instrument: 'animallow', note: 'jaguar' },
  // '&': { instrument: 'animallow', note: 'koala' },
  // '*': { instrument: 'animallow', note: 'leopard' },
  // '^': { instrument: 'animallow', note: 'lion' },
  // '#': { instrument: 'animallow', note: 'llama' },
  // '!': { instrument: 'animallow', note: 'longhorn' },
  // '@': { instrument: 'animallow', note: 'moose' },
  // '(': { instrument: 'animallow', note: 'ocelet' },
  // ')': { instrument: 'animallow', note: 'ostrich' },
  // '=': { instrument: 'animallow', note: 'owl' },
  // '~': { instrument: 'animallow', note: 'pig' },
  // '`': { instrument: 'animallow', note: 'tiger' },
  // '_': { instrument: 'animallow', note: 'walrus' },
  // '"': { instrument: 'animallow', note: 'alligator' },
  // "'": { instrument: 'animallow', note: 'angryowl' },
  // '<': { instrument: 'animallow', note: 'bear' },
  // '>': { instrument: 'animallow', note: 'cattle' },
  // '.': { instrument: 'animallow', note: 'cheeta' },
  // '?': { instrument: 'animallow', note: 'cow' },
  // '0': { instrument: 'animallow', note: 'deer' },
  // '1': { instrument: 'animallow', note: 'donkey' },
  // '2': { instrument: 'animallow', note: 'elephant' },
  // '3': { instrument: 'animallow', note: 'grizzlybear' },
  // '4': { instrument: 'animallow', note: 'hippo' },
  // '5': { instrument: 'animallow', note: 'hog' },
  // '6': { instrument: 'animallow', note: 'hyena' },
  // '7': { instrument: 'animallow', note: 'jaguar' },
  // '8': { instrument: 'animallow', note: 'koala' },
  // '9': { instrument: 'animallow', note: 'leopard' },

  's1': { instrument: 'animalbg', note: 'beach' },
  's2': { instrument: 'animalbg', note: 'db3' },
  's3': { instrument: 'animalbg', note: 'swamp' }
};
